/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EscrowVault {
      
    export type RemittanceStruct = {sender: AddressLike, recipient: AddressLike, amount: BigNumberish, fee: BigNumberish, createdAt: BigNumberish, expiresAt: BigNumberish, status: BigNumberish, corridor: string}

    export type RemittanceStructOutput = [sender: string, recipient: string, amount: bigint, fee: bigint, createdAt: bigint, expiresAt: bigint, status: bigint, corridor: string] & {sender: string, recipient: string, amount: bigint, fee: bigint, createdAt: bigint, expiresAt: bigint, status: bigint, corridor: string }
  
    }

  export interface EscrowVaultInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "AGENT_ROLE" | "DEFAULT_ADMIN_ROLE" | "createRemittance" | "feeCollector" | "getImpactStats" | "getRemittance" | "getRoleAdmin" | "grantAgentRole" | "grantRole" | "hasRole" | "pause" | "paused" | "refund" | "release" | "remittances" | "renounceRole" | "revokeRole" | "setFeeCollector" | "supportsInterface" | "totalSaved" | "totalVolume" | "unpause" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CircuitBreaker" | "Paused" | "RemittanceCreated" | "RemittanceRefunded" | "RemittanceReleased" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'AGENT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'createRemittance', values: [AddressLike, BigNumberish, BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getImpactStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRemittance', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantAgentRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'release', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'remittances', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeCollector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalSaved', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVolume', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'AGENT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createRemittance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getImpactStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemittance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAgentRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'remittances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSaved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace CircuitBreakerEvent {
      export type InputTuple = [triggeredBy: AddressLike];
      export type OutputTuple = [triggeredBy: string];
      export interface OutputObject {triggeredBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemittanceCreatedEvent {
      export type InputTuple = [id: BytesLike, sender: AddressLike, recipient: AddressLike, amount: BigNumberish, corridor: string];
      export type OutputTuple = [id: string, sender: string, recipient: string, amount: bigint, corridor: string];
      export interface OutputObject {id: string, sender: string, recipient: string, amount: bigint, corridor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemittanceRefundedEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemittanceReleasedEvent {
      export type InputTuple = [id: BytesLike, fee: BigNumberish];
      export type OutputTuple = [id: string, fee: bigint];
      export interface OutputObject {id: string, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowVault;
    waitForDeployment(): Promise<this>;

    interface: EscrowVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    AGENT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createRemittance: TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, feeBps: BigNumberish, corridor: string, ttl: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getImpactStats: TypedContractMethod<
      [],
      [[bigint, bigint] & {volume: bigint, saved: bigint }],
      'view'
    >
    

    
    getRemittance: TypedContractMethod<
      [id: BytesLike, ],
      [EscrowVault.RemittanceStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantAgentRole: TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    release: TypedContractMethod<
      [id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    remittances: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, string] & {sender: string, recipient: string, amount: bigint, fee: bigint, createdAt: bigint, expiresAt: bigint, status: bigint, corridor: string }],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeCollector: TypedContractMethod<
      [_new: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalSaved: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalVolume: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'AGENT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createRemittance'): TypedContractMethod<
      [recipient: AddressLike, amount: BigNumberish, feeBps: BigNumberish, corridor: string, ttl: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getImpactStats'): TypedContractMethod<
      [],
      [[bigint, bigint] & {volume: bigint, saved: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getRemittance'): TypedContractMethod<
      [id: BytesLike, ],
      [EscrowVault.RemittanceStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantAgentRole'): TypedContractMethod<
      [agent: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'remittances'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, string] & {sender: string, recipient: string, amount: bigint, fee: bigint, createdAt: bigint, expiresAt: bigint, status: bigint, corridor: string }],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeCollector'): TypedContractMethod<
      [_new: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalSaved'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalVolume'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CircuitBreaker'): TypedContractEvent<CircuitBreakerEvent.InputTuple, CircuitBreakerEvent.OutputTuple, CircuitBreakerEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RemittanceCreated'): TypedContractEvent<RemittanceCreatedEvent.InputTuple, RemittanceCreatedEvent.OutputTuple, RemittanceCreatedEvent.OutputObject>;
getEvent(key: 'RemittanceRefunded'): TypedContractEvent<RemittanceRefundedEvent.InputTuple, RemittanceRefundedEvent.OutputTuple, RemittanceRefundedEvent.OutputObject>;
getEvent(key: 'RemittanceReleased'): TypedContractEvent<RemittanceReleasedEvent.InputTuple, RemittanceReleasedEvent.OutputTuple, RemittanceReleasedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'CircuitBreaker(address)': TypedContractEvent<CircuitBreakerEvent.InputTuple, CircuitBreakerEvent.OutputTuple, CircuitBreakerEvent.OutputObject>;
      CircuitBreaker: TypedContractEvent<CircuitBreakerEvent.InputTuple, CircuitBreakerEvent.OutputTuple, CircuitBreakerEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RemittanceCreated(bytes32,address,address,uint256,string)': TypedContractEvent<RemittanceCreatedEvent.InputTuple, RemittanceCreatedEvent.OutputTuple, RemittanceCreatedEvent.OutputObject>;
      RemittanceCreated: TypedContractEvent<RemittanceCreatedEvent.InputTuple, RemittanceCreatedEvent.OutputTuple, RemittanceCreatedEvent.OutputObject>;
    

      'RemittanceRefunded(bytes32)': TypedContractEvent<RemittanceRefundedEvent.InputTuple, RemittanceRefundedEvent.OutputTuple, RemittanceRefundedEvent.OutputObject>;
      RemittanceRefunded: TypedContractEvent<RemittanceRefundedEvent.InputTuple, RemittanceRefundedEvent.OutputTuple, RemittanceRefundedEvent.OutputObject>;
    

      'RemittanceReleased(bytes32,uint256)': TypedContractEvent<RemittanceReleasedEvent.InputTuple, RemittanceReleasedEvent.OutputTuple, RemittanceReleasedEvent.OutputObject>;
      RemittanceReleased: TypedContractEvent<RemittanceReleasedEvent.InputTuple, RemittanceReleasedEvent.OutputTuple, RemittanceReleasedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }